function gui_b
	% Comment out the next line, then uncomment the lines
	% related to your OS
	%error('You must edit this file first!');

	% Use this line for Windows
	% Edit 'COM4' to match your port
	% (use serialportlist to list the serial ports visible from Matlab)
	h.port=serialport('COM6',921600);

	% Use this line for Linux
	% Edit '/dev/ttyUSB1' to match your port
	% (use serialportlist to list the serial ports visible from Matlab)
	% (also use "chmod 777 /dev/ttyUSB*" as root to enable access)
%	h.port=serialport('/dev/ttyUSB1',921600);

	% Use this line for Mac OS X
	% Edit '/dev/tty.usbserial-210376B5B9DC1' to match your port
	% (use serialportlist to list the serial ports visible from Matlab)
%	h.port=serialport('/dev/tty.usbserial-210376B5B9DC1',921600);

	% Initialize UIControls
	h.closefig=0;
	h.fig=figure('Position',[300 300 225 175]);% X Y W H
	set(h.fig,'CloseRequestFcn',@closefig);

	h.but34=uicontrol('Style','togglebutton',...
		'Enable','off',...
		'String','',...
		'Units','pixels',...
		'Position',[175 125 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','#DCDCDC');
	h.but33=uicontrol('Style','togglebutton',...
		'Enable','off',...
		'String','',...
		'Units','pixels',...
		'Position',[150 125 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','#DCDCDC');
	h.but32=uicontrol('Style','togglebutton',...
		'Enable','off',...
		'String','',...
		'Units','pixels',...
		'Position',[125 125 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','#DCDCDC');
	h.but31=uicontrol('Style','togglebutton',...
		'Enable','off',...
		'String','',...
		'Units','pixels',...
		'Position',[100 125 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','#DCDCDC');
	h.but30=uicontrol('Style','togglebutton',...
		'Enable','off',...
		'String','',...
		'Units','pixels',...
		'Position',[75 125 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','#DCDCDC');
	h.but29=uicontrol('Style','togglebutton',...
		'Enable','off',...
		'String','',...
		'Units','pixels',...
		'Position',[50 125 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','#DCDCDC');
	h.but28=uicontrol('Style','togglebutton',...
		'Enable','off',...
		'String','',...
		'Units','pixels',...
		'Position',[25 125 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','#DCDCDC');
	h.but27=uicontrol('Style','togglebutton',...
		'Enable','off',...
		'String','',...
		'Units','pixels',...
		'Position',[175 100 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','#DCDCDC');
	h.but26=uicontrol('Style','togglebutton',...
		'Enable','on',...
		'String','',...
		'Units','pixels',...
		'Position',[150 100 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','white');
	h.but25=uicontrol('Style','togglebutton',...
		'Enable','on',...
		'String','',...
		'Units','pixels',...
		'Position',[125 100 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','white');
	h.but24=uicontrol('Style','togglebutton',...
		'Enable','on',...
		'String','',...
		'Units','pixels',...
		'Position',[100 100 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','white');
	h.but23=uicontrol('Style','togglebutton',...
		'Enable','on',...
		'String','',...
		'Units','pixels',...
		'Position',[75 100 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','white');
	h.but22=uicontrol('Style','togglebutton',...
		'Enable','on',...
		'String','',...
		'Units','pixels',...
		'Position',[50 100 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','white');
	h.but21=uicontrol('Style','togglebutton',...
		'Enable','off',...
		'String','',...
		'Units','pixels',...
		'Position',[25 100 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','#DCDCDC');
	h.but20=uicontrol('Style','togglebutton',...
		'Enable','off',...
		'String','',...
		'Units','pixels',...
		'Position',[175 75 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','#DCDCDC');
	h.but19=uicontrol('Style','togglebutton',...
		'Enable','on',...
		'String','',...
		'Units','pixels',...
		'Position',[150 75 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','white');
	h.but18=uicontrol('Style','togglebutton',...
		'Enable','on',...
		'String','',...
		'Units','pixels',...
		'Position',[125 75 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','white');
	h.but17=uicontrol('Style','togglebutton',...
		'Enable','on',...
		'String','',...
		'Units','pixels',...
		'Position',[100 75 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','white');
	h.but16=uicontrol('Style','togglebutton',...
		'Enable','on',...
		'String','',...
		'Units','pixels',...
		'Position',[75 75 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','white');
	h.but15=uicontrol('Style','togglebutton',...
		'Enable','on',...
		'String','',...
		'Units','pixels',...
		'Position',[50 75 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','white');
	h.but14=uicontrol('Style','togglebutton',...
		'Enable','off',...
		'String','',...
		'Units','pixels',...
		'Position',[25 75 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','#DCDCDC');
	h.but13=uicontrol('Style','togglebutton',...
		'Enable','off',...
		'String','',...
		'Units','pixels',...
		'Position',[175 50 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','#DCDCDC');
	h.but12=uicontrol('Style','togglebutton',...
		'Enable','on',...
		'String','',...
		'Units','pixels',...
		'Position',[150 50 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','white');
	h.but11=uicontrol('Style','togglebutton',...
		'Enable','on',...
		'String','',...
		'Units','pixels',...
		'Position',[125 50 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','white');
	h.but10=uicontrol('Style','togglebutton',...
		'Enable','on',...
		'String','',...
		'Units','pixels',...
		'Position',[100 50 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','white');
	h.but9=uicontrol('Style','togglebutton',...
		'Enable','on',...
		'String','',...
		'Units','pixels',...
		'Position',[75 50 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','white');
	h.but8=uicontrol('Style','togglebutton',...
		'Enable','on',...
		'String','',...
		'Units','pixels',...
		'Position',[50 50 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','white');
	h.but7=uicontrol('Style','togglebutton',...
		'Enable','off',...
		'String','',...
		'Units','pixels',...
		'Position',[25 50 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','#DCDCDC');
	h.but6=uicontrol('Style','togglebutton',...
		'Enable','off',...
		'String','',...
		'Units','pixels',...
		'Position',[175 25 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','#DCDCDC');
	h.but5=uicontrol('Style','togglebutton',...
		'Enable','off',...
		'String','',...
		'Units','pixels',...
		'Position',[150 25 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','#DCDCDC');
	h.but4=uicontrol('Style','togglebutton',...
		'Enable','off',...
		'String','',...
		'Units','pixels',...
		'Position',[125 25 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','#DCDCDC');
	h.but3=uicontrol('Style','togglebutton',...
		'Enable','off',...
		'String','',...
		'Units','pixels',...
		'Position',[100 25 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','#DCDCDC');
	h.but2=uicontrol('Style','togglebutton',...
		'Enable','off',...
		'String','',...
		'Units','pixels',...
		'Position',[75 25 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','#DCDCDC');
	h.but1=uicontrol('Style','togglebutton',...
		'Enable','off',...
		'String','',...
		'Units','pixels',...
		'Position',[50 25 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','#DCDCDC');
	h.but0=uicontrol('Style','togglebutton',...
		'Enable','off',...
		'String','',...
		'Units','pixels',...
		'Position',[25 25 25 25],...
		'FontUnits','pixels',...
		'FontSize',20,...
		'BackgroundColor','#DCDCDC');

	% Set units to normalized to make the window extensible
	set(h.but34,'Units','normalized');
	set(h.but34,'FontUnits','normalized');
	set(h.but33,'Units','normalized');
	set(h.but33,'FontUnits','normalized');
	set(h.but32,'Units','normalized');
	set(h.but32,'FontUnits','normalized');
	set(h.but31,'Units','normalized');
	set(h.but31,'FontUnits','normalized');
	set(h.but30,'Units','normalized');
	set(h.but30,'FontUnits','normalized');
	set(h.but29,'Units','normalized');
	set(h.but29,'FontUnits','normalized');
	set(h.but28,'Units','normalized');
	set(h.but28,'FontUnits','normalized');
	set(h.but27,'Units','normalized');
	set(h.but27,'FontUnits','normalized');
	set(h.but26,'Units','normalized');
	set(h.but26,'FontUnits','normalized');
	set(h.but25,'Units','normalized');
	set(h.but25,'FontUnits','normalized');
	set(h.but24,'Units','normalized');
	set(h.but24,'FontUnits','normalized');
	set(h.but23,'Units','normalized');
	set(h.but23,'FontUnits','normalized');
	set(h.but22,'Units','normalized');
	set(h.but22,'FontUnits','normalized');
	set(h.but21,'Units','normalized');
	set(h.but21,'FontUnits','normalized');
	set(h.but20,'Units','normalized');
	set(h.but20,'FontUnits','normalized');
	set(h.but19,'Units','normalized');
	set(h.but19,'FontUnits','normalized');
	set(h.but18,'Units','normalized');
	set(h.but18,'FontUnits','normalized');
	set(h.but17,'Units','normalized');
	set(h.but17,'FontUnits','normalized');
	set(h.but16,'Units','normalized');
	set(h.but16,'FontUnits','normalized');
	set(h.but15,'Units','normalized');
	set(h.but15,'FontUnits','normalized');
	set(h.but14,'Units','normalized');
	set(h.but14,'FontUnits','normalized');
	set(h.but13,'Units','normalized');
	set(h.but13,'FontUnits','normalized');
	set(h.but12,'Units','normalized');
	set(h.but12,'FontUnits','normalized');
	set(h.but11,'Units','normalized');
	set(h.but11,'FontUnits','normalized');
	set(h.but10,'Units','normalized');
	set(h.but10,'FontUnits','normalized');
	set(h.but9,'Units','normalized');
	set(h.but9,'FontUnits','normalized');
	set(h.but8,'Units','normalized');
	set(h.but8,'FontUnits','normalized');
	set(h.but7,'Units','normalized');
	set(h.but7,'FontUnits','normalized');
	set(h.but6,'Units','normalized');
	set(h.but6,'FontUnits','normalized');
	set(h.but5,'Units','normalized');
	set(h.but5,'FontUnits','normalized');
	set(h.but4,'Units','normalized');
	set(h.but4,'FontUnits','normalized');
	set(h.but3,'Units','normalized');
	set(h.but3,'FontUnits','normalized');
	set(h.but2,'Units','normalized');
	set(h.but2,'FontUnits','normalized');
	set(h.but1,'Units','normalized');
	set(h.but1,'FontUnits','normalized');
	set(h.but0,'Units','normalized');
	set(h.but0,'FontUnits','normalized');

	% Main loop
	h.error='';
	while true
		% Check for a close figure request
		if (h.closefig==1)
			break;
		end

		% Poll each button and set or clear the corresponding RE bit
		leds=[0 0 0 0 0];
		if get(h.but34,'Value')
			leds(5)=bitset(leds(5),7);
			set(h.but34,'BackgroundColor','green');
		else
			set(h.but34,'BackgroundColor','#DCDCDC');
		end
		if get(h.but33,'Value')
			leds(5)=bitset(leds(5),6);
			set(h.but33,'BackgroundColor','green');
		else
			set(h.but33,'BackgroundColor','#DCDCDC');
		end
		if get(h.but32,'Value')
			leds(5)=bitset(leds(5),5);
			set(h.but32,'BackgroundColor','green');
		else
			set(h.but32,'BackgroundColor','#DCDCDC');
		end
		if get(h.but31,'Value')
			leds(5)=bitset(leds(5),4);
			set(h.but31,'BackgroundColor','green');
		else
			set(h.but31,'BackgroundColor','#DCDCDC');
		end
		if get(h.but30,'Value')
			leds(5)=bitset(leds(5),3);
			set(h.but30,'BackgroundColor','green');
		else
			set(h.but30,'BackgroundColor','#DCDCDC');
		end
		if get(h.but29,'Value')
			leds(5)=bitset(leds(5),2);
			set(h.but29,'BackgroundColor','green');
		else
			set(h.but29,'BackgroundColor','#DCDCDC');
		end
		if get(h.but28,'Value')
			leds(5)=bitset(leds(5),1);
			set(h.but28,'BackgroundColor','green');
		else
			set(h.but28,'BackgroundColor','#DCDCDC');
		end
		if get(h.but27,'Value')
			leds(4)=bitset(leds(4),7);
			set(h.but27,'BackgroundColor','green');
		else
			set(h.but27,'BackgroundColor','#DCDCDC');
		end
		if get(h.but26,'Value')
			leds(4)=bitset(leds(4),6);
			set(h.but26,'BackgroundColor','green');
		else
			set(h.but26,'BackgroundColor','white');
		end
		if get(h.but25,'Value')
			leds(4)=bitset(leds(4),5);
			set(h.but25,'BackgroundColor','green');
		else
			set(h.but25,'BackgroundColor','white');
		end
		if get(h.but24,'Value')
			leds(4)=bitset(leds(4),4);
			set(h.but24,'BackgroundColor','green');
		else
			set(h.but24,'BackgroundColor','white');
		end
		if get(h.but23,'Value')
			leds(4)=bitset(leds(4),3);
			set(h.but23,'BackgroundColor','green');
		else
			set(h.but23,'BackgroundColor','white');
		end
		if get(h.but22,'Value')
			leds(4)=bitset(leds(4),2);
			set(h.but22,'BackgroundColor','green');
		else
			set(h.but22,'BackgroundColor','white');
		end
		if get(h.but21,'Value')
			leds(4)=bitset(leds(4),1);
			set(h.but21,'BackgroundColor','green');
		else
			set(h.but21,'BackgroundColor','#DCDCDC');
		end
		if get(h.but20,'Value')
			leds(3)=bitset(leds(3),7);
			set(h.but20,'BackgroundColor','green');
		else
			set(h.but20,'BackgroundColor','#DCDCDC');
		end
		if get(h.but19,'Value')
			leds(3)=bitset(leds(3),6);
			set(h.but19,'BackgroundColor','green');
		else
			set(h.but19,'BackgroundColor','white');
		end
		if get(h.but18,'Value')
			leds(3)=bitset(leds(3),5);
			set(h.but18,'BackgroundColor','green');
		else
			set(h.but18,'BackgroundColor','white');
		end
		if get(h.but17,'Value')
			leds(3)=bitset(leds(3),4);
			set(h.but17,'BackgroundColor','green');
		else
			set(h.but17,'BackgroundColor','white');
		end
		if get(h.but16,'Value')
			leds(3)=bitset(leds(3),3);
			set(h.but16,'BackgroundColor','green');
		else
			set(h.but16,'BackgroundColor','white');
		end
		if get(h.but15,'Value')
			leds(3)=bitset(leds(3),2);
			set(h.but15,'BackgroundColor','green');
		else
			set(h.but15,'BackgroundColor','white');
		end
		if get(h.but14,'Value')
			leds(3)=bitset(leds(3),1);
			set(h.but14,'BackgroundColor','green');
		else
			set(h.but14,'BackgroundColor','#DCDCDC');
		end
		if get(h.but13,'Value')
			leds(2)=bitset(leds(2),7);
			set(h.but13,'BackgroundColor','green');
		else
			set(h.but13,'BackgroundColor','#DCDCDC');
		end
		if get(h.but12,'Value')
			leds(2)=bitset(leds(2),6);
			set(h.but12,'BackgroundColor','green');
		else
			set(h.but12,'BackgroundColor','white');
		end
		if get(h.but11,'Value')
			leds(2)=bitset(leds(2),5);
			set(h.but11,'BackgroundColor','green');
		else
			set(h.but11,'BackgroundColor','white');
		end
		if get(h.but10,'Value')
			leds(2)=bitset(leds(2),4);
			set(h.but10,'BackgroundColor','green');
		else
			set(h.but10,'BackgroundColor','white');
		end
		if get(h.but9,'Value')
			leds(2)=bitset(leds(2),3);
			set(h.but9,'BackgroundColor','green');
		else
			set(h.but9,'BackgroundColor','white');
		end
		if get(h.but8,'Value')
			leds(2)=bitset(leds(2),2);
			set(h.but8,'BackgroundColor','green');
		else
			set(h.but8,'BackgroundColor','white');
		end
		if get(h.but7,'Value')
			leds(2)=bitset(leds(2),1);
			set(h.but7,'BackgroundColor','green');
		else
			set(h.but7,'BackgroundColor','#DCDCDC');
		end
		if get(h.but6,'Value')
			leds(1)=bitset(leds(1),7);
			set(h.but6,'BackgroundColor','green');
		else
			set(h.but6,'BackgroundColor','#DCDCDC');
		end
		if get(h.but5,'Value')
			leds(1)=bitset(leds(1),6);
			set(h.but5,'BackgroundColor','green');
		else
			set(h.but5,'BackgroundColor','#DCDCDC');
		end
		if get(h.but4,'Value')
			leds(1)=bitset(leds(1),5);
			set(h.but4,'BackgroundColor','green');
		else
			set(h.but4,'BackgroundColor','#DCDCDC');
		end
		if get(h.but3,'Value')
			leds(1)=bitset(leds(1),4);
			set(h.but3,'BackgroundColor','green');
		else
			set(h.but3,'BackgroundColor','#DCDCDC');
		end
		if get(h.but2,'Value')
			leds(1)=bitset(leds(1),3);
			set(h.but2,'BackgroundColor','green');
		else
			set(h.but2,'BackgroundColor','#DCDCDC');
		end
		if get(h.but1,'Value')
			leds(1)=bitset(leds(1),2);
			set(h.but1,'BackgroundColor','green');
		else
			set(h.but1,'BackgroundColor','#DCDCDC');
		end
		if get(h.but0,'Value')
			leds(1)=bitset(leds(1),1);
			set(h.but0,'BackgroundColor','green');
		else
			set(h.but0,'BackgroundColor','#DCDCDC');
		end

		% Send button state to FPGA
		leds(2)=bitset(leds(2),8);
		write(h.port,leds(2:4),'uint8');

		% Pause to prevent CPU saturation
		pause(0.02);

		% Update window
		drawnow;
	end

	% Clean up and exit
	clear h.port
	delete(h.fig);
	if (~isempty(h.error))
		error(h.error);
	end

	% Callbacks
	function closefig(~,~)
		h.closefig=1;
	end
end
